### ISSUE TITLE
ActionResult not used

### ISSUE THREAD

**Issue by improwise** [proudmonkey/ApiBoilerPlate#24]
Hi,

How come ActionResult / Task< ActionResult > isn't used in this project but instead more direct approaches like Task<SampleResponse>? Just curious if there is a special reason for it?

**Comment by proudmonkey** [comment]
The reason is it's returning the `ApiResponse` object directly instead of wrapping it with the IActionResult return types sucb as `BadRequest`, `NotFound`, `UnAuthorize` and etc. AutoWrapper now supports `IActionResult` so you should be able to use that instead of returning the object directly as Task. I'll update the same once I convert this to .NET 5. Thanks for brining this up! :)

**Comment by improwise** [comment]
Thanks for responding. So if you are not using AutoWrapper for one reason or another I guess you should use ActionResult instead?

**Comment by proudmonkey** [comment]
Ideally, Yes. In fact, regardless if you use AutoWrapper or not, you should use ActionResult to take advantage of the default return types that I mentioned. Again, AutoWrapper supports ActionResult now so you are not limited to returning an ApiResponse object.
