### ISSUE TITLE
Add some detail on creating a service from the built API

### ISSUE THREAD

**Issue by ewhitchu** [proudmonkey/ApiBoilerPlate#6]
Great effort! However, how do I create a Windows Service from the resultant exe file? Almost nowhere in the web that I can find, are there clear instructions for running a WebApi based on Net Core 3.1 as a Windows Service using either Kestrel or Http.Sys as the self host.
Our applications and WebAPIs have to be installed and run at our customers' sites and most tutorials and blogs that I can find provide little or no help with Publish and Deploy to third parties who may or may not have strong Devops skills. I have found some good ideas for changing the Program.cs to recognise if the app is running in debug mode or as a Windows Service, but these mostly apply to .Net Framework bases.
Can you add some information regarding this?

**Comment by proudmonkey** [comment]
@ewhitchu - That is interesting. I honestly haven't tried deploying a REST Api as a windows service, but I hope this article might give a head start: https://dotnetcoretutorials.com/2019/12/21/hosting-an-asp-net-core-web-app-as-a-windows-service-in-net-core-3/?_gl=1*1rcx7kw*_ga*YW1wLXhBQlNRN1lDSDhnZF9vVXRSV3pXZUduRDVGa3MydUtQeHNvcjkyZ2ViTXRZMllORENNTmNaUEdjZDBrTXpxejk.

Also, since your question isn't directly related to this project, please post your future query to forums such as stackoverflow or forums.asp.net to get more help from community members who might have experience with what you are trying to achieve. 

Thank so much! :)
